# YAML file for google cloud deployment

runtime: python310
env: flex
entrypoint: gunicorn -b :$PORT main:app


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6


resources:
  cpu: 4
  memory_gb: 5
  disk_size_gb: 20


liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2