from components.local_mask_generate import LocalMaskGen
from components.overlay_image import OverlayImage
from components.replicate_inpaint import ReplicateInPainting
from components.replicate_mask_generate import ReplicateMaskGen

